name: portfolio_admin
description: ポートフォリオサイトの管理アプリ

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  supabase_flutter: ^1.0.0
  image_picker: ^0.8.6
  image_picker_for_web: ^2.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - .env
